//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrmPractise02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int Attendanceid { get; set; }
        public Nullable<int> Uid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string checkin { get; set; }
        public string status { get; set; }
        public string checkout { get; set; }
    
        public virtual User User { get; set; }
    }
}
