//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrmPractise02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int EduID { get; set; }
        public Nullable<int> Uid { get; set; }
        public string Degree { get; set; }
        public string Institute { get; set; }
        public string Board { get; set; }
        public Nullable<int> Startdate { get; set; }
        public Nullable<int> Enddate { get; set; }
        public string hasaddededucation { get; set; }
    
        public virtual User User { get; set; }
    }
}
