//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrmPractise02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int ExpID { get; set; }
        public Nullable<int> Uid { get; set; }
        public string Company { get; set; }
        public string Title { get; set; }
        public string Startdate { get; set; }
        public string currentwork { get; set; }
        public string Enddate { get; set; }
        public string otherskill { get; set; }
    
        public virtual User User { get; set; }
    }
}
