//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrmPractise02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.JobApplications = new HashSet<JobApplication>();
        }
    
        public int Jid { get; set; }
        public string Title { get; set; }
        public string qualification { get; set; }
        public string Salary { get; set; }
        public string experience { get; set; }
        public string LastDateOfApply { get; set; }
        public string Location { get; set; }
        public string Description { get; set; }
        public Nullable<int> noofvacancie { get; set; }
        public string jobstatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApplication> JobApplications { get; set; }
    }
}
