//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrmPractise02
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobApplication()
        {
            this.Shortlists = new HashSet<Shortlist>();
            this.JobAssignments = new HashSet<JobAssignment>();
        }
    
        public int JobApplicationID { get; set; }
        public Nullable<int> Jid { get; set; }
        public Nullable<int> Uid { get; set; }
        public string name { get; set; }
        public string status { get; set; }
        public string shortlist { get; set; }
        public string DocumentPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shortlist> Shortlists { get; set; }
        public virtual User User { get; set; }
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobAssignment> JobAssignments { get; set; }
    }
}
