//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrmPractise02
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobremarkofmember
    {
        public int RemarkID { get; set; }
        public Nullable<int> CommitteeImemberId { get; set; }
        public Nullable<int> JobApplicationID { get; set; }
        public Nullable<int> Remarks { get; set; }
    
        public virtual CommitteeMember CommitteeMember { get; set; }
        public virtual JobApplication JobApplication { get; set; }
    }
}
