//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrmPractise02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Application
    {
        public int leaveappid { get; set; }
        public Nullable<int> Uid { get; set; }
        public string leavetype { get; set; }
        public string startdate { get; set; }
        public string enddate { get; set; }
        public string reason { get; set; }
        public string status { get; set; }
    
        public virtual User User { get; set; }
    }
}
