//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HrmPractise02
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PracticeHrmDBEntities : DbContext
    {
        public PracticeHrmDBEntities()
            : base("name=PracticeHrmDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Leave_Application> Leave_Application { get; set; }
        public virtual DbSet<Shortlist> Shortlists { get; set; }
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<JobApplication> JobApplications { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Experience> Experiences { get; set; }
    }
}
